# Generated by Django 4.1.2 on 2022-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
