# Generated by Django 4.1.2 on 2022-11-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
