# Generated by Django 4.1.2 on 2022-11-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dogs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='sex',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
