# Generated by Django 4.1.2 on 2022-11-30 02:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dogs_sex_alter_dogs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default='null', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogs',
            name='location',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogs',
            name='weight',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
    ]
