# Generated by Django 4.1.2 on 2022-11-30 02:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dogs_attributes_dogs_location_dogs_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default='null', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogs',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
